# Generated by Django 4.1.2 on 2022-10-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_brand_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
    ]
