# Generated by Django 4.1.2 on 2022-10-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_brand_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.PositiveIntegerField(),
        ),
    ]
